on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .vscode/*
name: Build
jobs:
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
            fetch-depth: 0
        - task: UsePythonVersion@0
          inputs:
            versionSpec: "3.8"
            addToPath: true
            architecture: "x64"
          displayName: "Use Python 3.8"

        - script: make ci-dependencies
          displayName: "Install dependencies"

        - script: make test
          displayName: "Run tests"

        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
                -Dsonar.organization=brunopenso
                -Dsonar.projectKey=9b6a84d1-544b-4413-8c39-bb02a0de21ea
                -Dsonar.python.coverage.reportPaths=coverage.xml
                -Dsonar.sources=src
                -Dsonar.coverage.exclusions=**tests**
                -Dsonar.language=py
